/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.AlunoModel;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author asg75
 */
public class TelaVizualizarAlunosView extends javax.swing.JPanel {

    /**
     * Creates new form TelaVizualizarAlunosTreinadorView
     */
    public TelaVizualizarAlunosView() {
        initComponents();
    }
    
    public void adicionarDadoTabela(ArrayList<AlunoModel> listaAlunos){
        DefaultTableModel model = (DefaultTableModel)tabAlunos.getModel();
        
        for(AlunoModel Aluno:listaAlunos){
            if(Aluno.getTreino() !=null){
                model.addRow(new Object[]{Aluno.getNome(),Aluno.getTreino(),Aluno.getHorarioDeTreino().toString(),Aluno.getCpf()});
            }
            else{
                model.addRow(new Object[]{Aluno.getNome(),"Aluno sem treino",Aluno.getHorarioDeTreino().toString(),Aluno.getCpf()});
            }
        }
    }
    public String getIdAlterarTreino(){
        return tfIdAlunoAlterarTreino.getText();
    }
    public String getTituloDoTreino (){
        return tfTituloDoTreino.getText();
    }
    public void adicionarAcaoBotaoAlterarTreino(ActionListener acao){
        btAlterarTreino.addActionListener(acao);
    }
    public String IdAlterarHorario(){
        return tfIdAlterarHorario.getText();
    }
    public int getHora(){
        return (int)spnHora.getValue();
    }
    public int getMinutos(){
        return (int)spnMinuto.getValue();
    }
    public void adicionarAcaoAlterarHorario(ActionListener acao){
        btAlterarHorario.addActionListener(acao);
    }
    public void limparDados(){
        tfIdAlterarHorario.setText(null);
        tfIdAlunoAlterarTreino.setText(null);
        tfTituloDoTreino.setText(null);
    }
    public void ExibirMensagem(String mensagem){
        JOptionPane.showMessageDialog(null, mensagem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        lbVizualizarAlunos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabAlunos = new javax.swing.JTable();
        btAlterarTreino = new javax.swing.JButton();
        lbAlterarTreino = new javax.swing.JLabel();
        lbIDAlutoAlterarTreino = new javax.swing.JLabel();
        tfIdAlunoAlterarTreino = new javax.swing.JTextField();
        lbTituloDoTreino = new javax.swing.JLabel();
        tfTituloDoTreino = new javax.swing.JTextField();
        lbAlterarHorario = new javax.swing.JLabel();
        tfIdAlterarHorario = new javax.swing.JTextField();
        lbIdAlunoAlterarHorario = new javax.swing.JLabel();
        spnHora = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btAlterarHorario = new javax.swing.JButton();
        spnMinuto = new javax.swing.JSpinner();

        lbVizualizarAlunos.setText("Vizualizar alunos");

        tabAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Treino", "Horario", "ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabAlunos);

        btAlterarTreino.setText("Alterar Treino");

        lbAlterarTreino.setText("Alterar Treino");

        lbIDAlutoAlterarTreino.setText("ID do aluno");

        lbTituloDoTreino.setText("TituloDoTreino");

        lbAlterarHorario.setText("Alterar Horario");

        lbIdAlunoAlterarHorario.setText("ID do aluno");

        spnHora.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));

        jLabel1.setText("Hora");

        jLabel2.setText("Minuto");

        btAlterarHorario.setText("Alterar Horario");

        spnMinuto.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(lbVizualizarAlunos)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(19, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbAlterarTreino)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tfIdAlunoAlterarTreino, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbIDAlutoAlterarTreino, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbTituloDoTreino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfTituloDoTreino))
                                .addGap(29, 29, 29)
                                .addComponent(btAlterarTreino))
                            .addComponent(lbAlterarHorario)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tfIdAlterarHorario, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbIdAlunoAlterarHorario, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(37, 37, 37)
                                        .addComponent(jLabel2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(spnHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(spnMinuto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btAlterarHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 5, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbVizualizarAlunos)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbAlterarTreino)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbIDAlutoAlterarTreino)
                    .addComponent(lbTituloDoTreino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfIdAlunoAlterarTreino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTituloDoTreino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAlterarTreino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbAlterarHorario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbIdAlunoAlterarHorario)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfIdAlterarHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAlterarHorario)
                    .addComponent(spnMinuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterarHorario;
    private javax.swing.JButton btAlterarTreino;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel lbAlterarHorario;
    private javax.swing.JLabel lbAlterarTreino;
    private javax.swing.JLabel lbIDAlutoAlterarTreino;
    private javax.swing.JLabel lbIdAlunoAlterarHorario;
    private javax.swing.JLabel lbTituloDoTreino;
    private javax.swing.JLabel lbVizualizarAlunos;
    private javax.swing.JSpinner spnHora;
    private javax.swing.JSpinner spnMinuto;
    private javax.swing.JTable tabAlunos;
    private javax.swing.JTextField tfIdAlterarHorario;
    private javax.swing.JTextField tfIdAlunoAlterarTreino;
    private javax.swing.JTextField tfTituloDoTreino;
    // End of variables declaration//GEN-END:variables
}
