/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

//import Model.InstrutorModel;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author asg75
 */
public class TelaListarFuncionariosView extends javax.swing.JPanel {

    /**
     * Creates new form TelaListarFuncionariosView
     */
    public TelaListarFuncionariosView() {
        initComponents();
    }

    public String getId(){
        return tfIdVizualizarPontosBatidos.getText();
    }
    
    public void setTextAreaVisualizarPontos(String text){
        taPontos.setText(text);
    }
    
//    public void setDadosTable(ArrayList<InstrutorModel> listaFuncionarios){
//        DefaultTableModel model = (DefaultTableModel)tabFuncionarios.getModel();
//        
//        for(InstrutorModel instrutor:listaFuncionarios){
//            model.addRow(new Object[]{instrutor.getNome(), instrutor.getCpf()});
//        }
//    };
    public void ExibirMensagem(String mensagem){
        JOptionPane.showMessageDialog(null, mensagem);
    }
    public void limparTextField(){
        tfIdVizualizarPontosBatidos.setText(null);
    }
    public void addAcaoBotaoVizualisarPontos(ActionListener acao){
        btVisualizarPontosBatidos.addActionListener(acao);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbListarFuncionarios = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabFuncionarios = new javax.swing.JTable();
        btVisualizarPontosBatidos = new javax.swing.JButton();
        tfIdVizualizarPontosBatidos = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        taPontosBatidos = new javax.swing.JScrollPane();
        taPontos = new javax.swing.JTextArea();

        lbListarFuncionarios.setText("Listar funcionarios");

        tabFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabFuncionarios);

        btVisualizarPontosBatidos.setText("visualizar pontos batidos");

        jLabel1.setText("ID:");

        taPontos.setColumns(20);
        taPontos.setRows(5);
        taPontosBatidos.setViewportView(taPontos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(taPontosBatidos)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(tfIdVizualizarPontosBatidos, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btVisualizarPontosBatidos))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbListarFuncionarios)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1))
                        .addGap(0, 5, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbListarFuncionarios)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btVisualizarPontosBatidos)
                    .addComponent(tfIdVizualizarPontosBatidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(taPontosBatidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btVisualizarPontosBatidos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbListarFuncionarios;
    private javax.swing.JTextArea taPontos;
    private javax.swing.JScrollPane taPontosBatidos;
    private javax.swing.JTable tabFuncionarios;
    private javax.swing.JTextField tfIdVizualizarPontosBatidos;
    // End of variables declaration//GEN-END:variables
}
