/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author asg75
 */
public class TelaInicialGerenteView extends javax.swing.JPanel {

    /**
     * Creates new form TelaInicialGerenteView
     */
    public TelaInicialGerenteView() {
        initComponents();
    }
    public void setNomeGerente(String nome){
        lbNomeGerente.setText(nome);
    }
    public void addAcaoBotaoAlterarSenha(ActionListener acao){
        btAlterarSenha.addActionListener(acao);
    }
    public void addAcaoBotaoListarAlunos(ActionListener acao){
        btListarAlunos.addActionListener(acao);
    }
    public void addAcaoBotaoListarFuncionarios(ActionListener acao){
        btListarFuncionarios.addActionListener(acao);
    }
    public void addAcaoBotaoRegistrar(ActionListener acao){
        btRegistrar.addActionListener(acao);
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        lbNomeGerente = new javax.swing.JLabel();
        btListarFuncionarios = new javax.swing.JButton();
        btListarAlunos = new javax.swing.JButton();
        btRegistrar = new javax.swing.JButton();
        btAlterarSenha = new javax.swing.JButton();

        jButton3.setText("jButton3");
        jButton3.setActionCommand("Registrar");

        lbNomeGerente.setText("Nome do gerente");

        btListarFuncionarios.setText("Listar funcionarios");

        btListarAlunos.setText("Listar Alunos");

        btRegistrar.setText("Registrar");

        btAlterarSenha.setText("Alterar Senha");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btListarAlunos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btListarFuncionarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btAlterarSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(163, 163, 163))
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(lbNomeGerente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lbNomeGerente)
                .addGap(31, 31, 31)
                .addComponent(btListarFuncionarios)
                .addGap(18, 18, 18)
                .addComponent(btListarAlunos)
                .addGap(18, 18, 18)
                .addComponent(btRegistrar)
                .addGap(18, 18, 18)
                .addComponent(btAlterarSenha)
                .addContainerGap(77, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterarSenha;
    private javax.swing.JButton btListarAlunos;
    private javax.swing.JButton btListarFuncionarios;
    private javax.swing.JButton btRegistrar;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel lbNomeGerente;
    // End of variables declaration//GEN-END:variables
}
