/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author asg75
 */
public class TelaRegistrarInstutor extends javax.swing.JPanel {

    /**
     * Creates new form TelaRegistrarInstutor
     */
    public TelaRegistrarInstutor() {
        initComponents();
    }
    
    public Calendar[] HorariosDeTrabalho(){
        Calendar[] horariosDeTrabalho = new Calendar[7];

            Calendar horarioDomingo = Calendar.getInstance();
            horarioDomingo.set(Calendar.HOUR_OF_DAY, (Integer) spHoraDomingo.getValue());
            horarioDomingo.set(Calendar.MINUTE, (Integer) spnMinutosDomingo.getValue());
            horariosDeTrabalho[0] = horarioDomingo;
            Calendar horarioSegunda = Calendar.getInstance();
            horarioSegunda.set(Calendar.HOUR_OF_DAY, (Integer) spHoraSegunda.getValue());
            horarioSegunda.set(Calendar.MINUTE, (Integer) spMinutosSegunda.getValue());
            horariosDeTrabalho[1] = horarioSegunda;
            Calendar horarioTerca = Calendar.getInstance();
            horarioTerca.set(Calendar.HOUR_OF_DAY, (Integer) spHoraTerca.getValue());
            horarioTerca.set(Calendar.MINUTE, (Integer) spnMinutosTerca.getValue());
            horariosDeTrabalho[2] = horarioTerca;
            Calendar horarioQuarta = Calendar.getInstance();
            horarioQuarta.set(Calendar.HOUR_OF_DAY, (Integer) spHoraQuarta.getValue());
            horarioQuarta.set(Calendar.MINUTE, (Integer) spnMinutosQuarta.getValue());
            horariosDeTrabalho[3] = horarioTerca;
            Calendar horarioQuinta = Calendar.getInstance();
            horarioQuinta.set(Calendar.HOUR_OF_DAY, (Integer) spHoraQuinta.getValue());
            horarioQuinta.set(Calendar.MINUTE, (Integer) spnMinutosQuinta.getValue());
            horariosDeTrabalho[4] = horarioQuinta;
            Calendar horarioSexta = Calendar.getInstance();
            horarioSexta.set(Calendar.HOUR_OF_DAY, (Integer) spHoraSexta.getValue());
            horarioSexta.set(Calendar.MINUTE, (Integer) spnMinutosSexta.getValue());
            horariosDeTrabalho[5] = horarioSexta;
            Calendar horarioSabado = Calendar.getInstance();
            horarioSabado.set(Calendar.HOUR_OF_DAY, (Integer) spHoraSabado.getValue());
            horarioSabado.set(Calendar.MINUTE, (Integer) spnMinutosSabado.getValue());
            horariosDeTrabalho[6] = horarioSabado;
            
        return horariosDeTrabalho;
    }
    
    public void addAcaoBotaoSalvar(ActionListener acao){
        btSalvar.addActionListener(acao);
    }
    
    public void ExibirMensagem(String mensagem){
        JOptionPane.showMessageDialog(null, mensagem);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbHorariosDeTrabalho = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        spHoraSexta = new javax.swing.JSpinner();
        spnMinutosSexta = new javax.swing.JSpinner();
        spnMinutosQuinta = new javax.swing.JSpinner();
        spHoraQuinta = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        spHoraQuarta = new javax.swing.JSpinner();
        spnMinutosQuarta = new javax.swing.JSpinner();
        spnMinutosTerca = new javax.swing.JSpinner();
        spMinutosSegunda = new javax.swing.JSpinner();
        spHoraTerca = new javax.swing.JSpinner();
        spHoraSegunda = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        lbsegundaFeira = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        spHoraSabado = new javax.swing.JSpinner();
        spnMinutosSabado = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        spHoraDomingo = new javax.swing.JSpinner();
        spnMinutosDomingo = new javax.swing.JSpinner();
        btSalvar = new javax.swing.JButton();
        lbHora = new javax.swing.JLabel();
        lbMinuto = new javax.swing.JLabel();

        lbHorariosDeTrabalho.setText("Horarios De Trabalho");

        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Sexta-feira");

        spHoraSexta.setModel(new javax.swing.SpinnerNumberModel(0, 0, 24, 1));

        spnMinutosSexta.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        spnMinutosQuinta.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        spHoraQuinta.setModel(new javax.swing.SpinnerNumberModel(0, 0, 24, 1));

        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Quinta-feira");

        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Quarta-feira");

        spHoraQuarta.setModel(new javax.swing.SpinnerNumberModel(0, 0, 24, 1));

        spnMinutosQuarta.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        spnMinutosTerca.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        spMinutosSegunda.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        spHoraTerca.setModel(new javax.swing.SpinnerNumberModel(0, 0, 24, 1));

        spHoraSegunda.setModel(new javax.swing.SpinnerNumberModel(0, 0, 24, 1));
        spHoraSegunda.setToolTipText("");

        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Terça-feira");

        lbsegundaFeira.setForeground(new java.awt.Color(51, 51, 51));
        lbsegundaFeira.setText("Segunda-feira");

        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Sábado");

        spHoraSabado.setModel(new javax.swing.SpinnerNumberModel(0, 0, 24, 1));

        spnMinutosSabado.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Domingo");

        spHoraDomingo.setModel(new javax.swing.SpinnerNumberModel(0, 0, 24, 1));

        spnMinutosDomingo.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        btSalvar.setText("Salvar");

        lbHora.setText("Hora");

        lbMinuto.setText("Minuto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbHorariosDeTrabalho)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btSalvar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(lbsegundaFeira))
                .addGap(18, 158, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(spHoraDomingo)
                        .addComponent(spHoraSabado)
                        .addComponent(spHoraSexta)
                        .addComponent(spHoraQuinta)
                        .addComponent(spHoraQuarta)
                        .addComponent(spHoraSegunda)
                        .addComponent(spHoraTerca))
                    .addComponent(lbHora))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbMinuto)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(spMinutosSegunda)
                        .addComponent(spnMinutosDomingo)
                        .addComponent(spnMinutosSabado)
                        .addComponent(spnMinutosSexta)
                        .addComponent(spnMinutosQuinta)
                        .addComponent(spnMinutosQuarta)
                        .addComponent(spnMinutosTerca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lbHorariosDeTrabalho)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHora)
                    .addComponent(lbMinuto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spMinutosSegunda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spHoraSegunda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbsegundaFeira, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel6))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(spHoraTerca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(spnMinutosTerca, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(spHoraQuarta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(spnMinutosQuarta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(spHoraQuinta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(spnMinutosQuinta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(spHoraSexta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(spnMinutosSexta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel9))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(spHoraSabado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(spnMinutosSabado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel10))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(spnMinutosDomingo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(spHoraDomingo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btSalvar)
                .addGap(52, 52, 52))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSalvar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbHora;
    private javax.swing.JLabel lbHorariosDeTrabalho;
    private javax.swing.JLabel lbMinuto;
    private javax.swing.JLabel lbsegundaFeira;
    private javax.swing.JSpinner spHoraDomingo;
    private javax.swing.JSpinner spHoraQuarta;
    private javax.swing.JSpinner spHoraQuinta;
    private javax.swing.JSpinner spHoraSabado;
    private javax.swing.JSpinner spHoraSegunda;
    private javax.swing.JSpinner spHoraSexta;
    private javax.swing.JSpinner spHoraTerca;
    private javax.swing.JSpinner spMinutosSegunda;
    private javax.swing.JSpinner spnMinutosDomingo;
    private javax.swing.JSpinner spnMinutosQuarta;
    private javax.swing.JSpinner spnMinutosQuinta;
    private javax.swing.JSpinner spnMinutosSabado;
    private javax.swing.JSpinner spnMinutosSexta;
    private javax.swing.JSpinner spnMinutosTerca;
    // End of variables declaration//GEN-END:variables
}
