/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;

/**
 *
 * @author asg75
 */
public class TelaInicialTreinadorView extends javax.swing.JPanel {

    /**
     * Creates new form TelaInicialGerenteView
     */
    public TelaInicialTreinadorView() {
        initComponents();
    }
    
    public void setNome(String nome){
        lbNome.setText(nome);
    }
    public void addAcaoBotaoAdicionar(ActionListener acao){
        btAdicionarTreino.addActionListener(acao);
    }
    public void addAcaoBaterPonto(ActionListener acao){
        btBaterPonto.addActionListener(acao);
    }
    public void addAcaoVisualizarAlunos(ActionListener acao){
        btVisualizarAlunos.addActionListener(acao);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbNome = new javax.swing.JLabel();
        btVisualizarAlunos = new javax.swing.JButton();
        btBaterPonto = new javax.swing.JButton();
        btAdicionarTreino = new javax.swing.JButton();

        lbNome.setText("Nome do treinador");

        btVisualizarAlunos.setText("Vizualizar Alunos");

        btBaterPonto.setText("Bater Ponto");
        btBaterPonto.setToolTipText("");

        btAdicionarTreino.setText("AdicionarTreino");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(133, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btBaterPonto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btVisualizarAlunos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lbNome))
                    .addComponent(btAdicionarTreino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(156, 156, 156))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lbNome)
                .addGap(38, 38, 38)
                .addComponent(btVisualizarAlunos)
                .addGap(41, 41, 41)
                .addComponent(btBaterPonto)
                .addGap(40, 40, 40)
                .addComponent(btAdicionarTreino)
                .addContainerGap(77, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionarTreino;
    private javax.swing.JButton btBaterPonto;
    private javax.swing.JButton btVisualizarAlunos;
    private javax.swing.JLabel lbNome;
    // End of variables declaration//GEN-END:variables
}
