/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author asg75
 */
public class TelaInicialAlunoView extends javax.swing.JPanel {

    /**
     * Creates new form TelaInicialAlunoView
     */
    public TelaInicialAlunoView() {
        initComponents();
    }
    
    public void SetTreino(String nome, String tituloDoTreino, String descricaoDoTreino){
        LbNome.setText(nome);
        LbTituloDoTreino.setText(tituloDoTreino);
        taDescricaoDoTreino.setText(descricaoDoTreino);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LbNome = new javax.swing.JLabel();
        LbTituloDoTreino = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDescricaoDoTreino = new javax.swing.JTextArea();
        lbDescricao = new javax.swing.JLabel();

        LbNome.setText("Nome");

        LbTituloDoTreino.setText("Titulo do treino");
        LbTituloDoTreino.setToolTipText("");

        taDescricaoDoTreino.setColumns(20);
        taDescricaoDoTreino.setRows(5);
        jScrollPane1.setViewportView(taDescricaoDoTreino);

        lbDescricao.setText("Descrição do treino:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(LbNome)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(157, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(LbTituloDoTreino)
                        .addGap(162, 162, 162))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbDescricao)
                        .addGap(151, 151, 151))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LbNome)
                .addGap(19, 19, 19)
                .addComponent(LbTituloDoTreino)
                .addGap(21, 21, 21)
                .addComponent(lbDescricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LbNome;
    private javax.swing.JLabel LbTituloDoTreino;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbDescricao;
    private javax.swing.JTextArea taDescricaoDoTreino;
    // End of variables declaration//GEN-END:variables
}
